In [1]:
#importing the Libraies
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
# Reading the Dataset
dataset = pd.read_csv('CKD.csv')

In [3]:
dataset

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,2.000000,76.459948,c,3.0,0.0,normal,abnormal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,yes,no,yes
1,3.000000,76.459948,c,2.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,34.000000,12300.000000,4.705597,no,no,no,yes,poor,no,yes
2,4.000000,76.459948,a,1.0,0.0,normal,normal,notpresent,notpresent,99.000000,...,34.000000,8408.191126,4.705597,no,no,no,yes,poor,no,yes
3,5.000000,76.459948,d,1.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,poor,yes,yes
4,5.000000,50.000000,c,0.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,36.000000,12400.000000,4.705597,no,no,no,yes,poor,no,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,219.000000,...,37.000000,9800.000000,4.400000,no,no,no,yes,poor,no,yes
395,51.492308,70.000000,c,0.0,2.0,normal,normal,notpresent,notpresent,220.000000,...,27.000000,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
396,51.492308,70.000000,c,3.0,0.0,normal,normal,notpresent,notpresent,110.000000,...,26.000000,9200.000000,3.400000,yes,yes,no,poor,poor,no,yes
397,51.492308,90.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,207.000000,...,38.868902,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
398,51.492308,80.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,100.000000,...,53.000000,8500.000000,4.900000,no,no,no,yes,poor,no,no

In [4]:
print(dataset.columns)

Index(['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr', 'bu',
       'sc', 'sod', 'pot', 'hrmo', 'pcv', 'wc', 'rc', 'htn', 'dm', 'cad',
       'appet', 'pe', 'ane', 'classification'],
      dtype='object')

In [5]:
dataset=pd.get_dummies(dataset,drop_first=True)

In [6]:
dataset

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes,classification_yes
0,2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,False,False,False,False,False,False,True,True,False,True
1,3.000000,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,True,False,False,False,False,False,True,False,False,True
2,4.000000,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,True,False,False,False,False,False,True,False,False,True
3,5.000000,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,True,False,False,False,False,False,True,False,True,True
4,5.000000,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,True,False,False,False,False,False,True,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0.0,0.0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,...,True,False,False,False,False,False,True,False,False,True
395,51.492308,70.000000,0.0,2.0,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,...,True,False,False,True,True,False,True,False,True,True
396,51.492308,70.000000,3.0,0.0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,...,True,False,False,True,True,False,False,False,False,True
397,51.492308,90.000000,0.0,0.0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,...,True,False,False,True,True,False,True,False,True,True
398,51.492308,80.000000,0.0,0.0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,...,True,False,False,False,False,False,True,False,False,False

In [7]:
#X (Input features):
indep=dataset[['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes', ]]
dep=dataset['classification_yes']

In [8]:
indep

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,rbc_normal,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes
0,2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,True,False,False,False,False,False,False,True,True,False
1,3.000000,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,True,True,False,False,False,False,False,True,False,False
2,4.000000,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,True,True,False,False,False,False,False,True,False,False
3,5.000000,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,True,True,False,False,False,False,False,True,False,True
4,5.000000,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,True,True,False,False,False,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0.0,0.0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,...,True,True,False,False,False,False,False,True,False,False
395,51.492308,70.000000,0.0,2.0,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,...,True,True,False,False,True,True,False,True,False,True
396,51.492308,70.000000,3.0,0.0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,...,True,True,False,False,True,True,False,False,False,False
397,51.492308,90.000000,0.0,0.0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,...,True,True,False,False,True,True,False,True,False,True
398,51.492308,80.000000,0.0,0.0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,...,True,True,False,False,False,False,False,True,False,False

In [9]:
dep

0       True
1       True
2       True
3       True
4       True
       ...
394     True
395     True
396     True
397     True
398    False
Name: classification_yes, Length: 399, dtype: bool

In [10]:
#split into training set and test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(indep, dep, test_size = 1/3, random_state = 0)

In [11]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [12]:
from sklearn.tree import DecisionTreeClassifier

In [13]:
from sklearn.model_selection import GridSearchCV

param_grid = {'criterion':['gini','entropy'],
              'max_features': ['auto','sqrt','log2'],
              'splitter':['best','random']} 



grid = GridSearchCV(DecisionTreeClassifier(), param_grid, refit = True, verbose = 3,n_jobs=-1,scoring='f1_weighted') 
   
# fitting the model for grid search 
grid.fit(X_train, y_train)

Fitting 5 folds for each of 12 candidates, totalling 60 fits

GridSearchCV(estimator=DecisionTreeClassifier(), n_jobs=-1,
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'splitter': ['best', 'random']},
             scoring='f1_weighted', verbose=3)

In [15]:
# print best parameter after tuning 
#print(grid.best_params_) 
re=grid.cv_results_
#print(re)
grid_predictions = grid.predict(X_test) 
   

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, grid_predictions)



# print classification report 
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, grid_predictions)

In [16]:

from sklearn.metrics import f1_score
f1_macro=f1_score(y_test,grid_predictions,average='weighted')
print("The f1_macro value for best parameter {}:".format(grid.best_params_),f1_macro)

The f1_macro value for best parameter {'criterion': 'entropy', 'max_features': 'log2', 'splitter': 'random'}: 0.9924946382275899

In [17]:
print("The confusion Matrix:\n",cm)

The confusion Matrix:
 [[51  0]
 [ 1 81]]

In [19]:
print("The report:\n",clf_report)

The report:
               precision    recall  f1-score   support

       False       0.98      1.00      0.99        51
        True       1.00      0.99      0.99        82

    accuracy                           0.99       133
   macro avg       0.99      0.99      0.99       133
weighted avg       0.99      0.99      0.99       133

In [21]:
print("The report:\n",clf_report)

The report:
               precision    recall  f1-score   support

       False       0.98      1.00      0.99        51
        True       1.00      0.99      0.99        82

    accuracy                           0.99       133
   macro avg       0.99      0.99      0.99       133
weighted avg       0.99      0.99      0.99       133

In [20]:
from sklearn.metrics import roc_auc_score

roc_auc_score(y_test,grid.predict_proba(X_test)[:,1])

0.9939024390243902

In [21]:
table=pd.DataFrame.from_dict(re)

In [22]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_splitter,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.018285,0.006979,0.006425,0.000805,gini,auto,best,"{'criterion': 'gini', 'max_features': 'auto', ...",0.945100,0.924528,0.907035,0.943093,0.943093,0.932570,0.014800,11
1,0.009087,0.001674,0.005823,0.001141,gini,auto,random,"{'criterion': 'gini', 'max_features': 'auto', ...",0.925035,0.961755,0.981217,0.906705,0.943651,0.943673,0.026270,9
2,0.004771,0.001033,0.005992,0.001342,gini,sqrt,best,"{'criterion': 'gini', 'max_features': 'sqrt', ...",0.926978,0.962264,0.925524,0.903887,0.981031,0.939937,0.027794,10
3,0.003815,0.000190,0.005273,0.000925,gini,sqrt,random,"{'criterion': 'gini', 'max_features': 'sqrt', ...",0.926567,0.981014,0.981217,0.981217,0.981217,0.970246,0.021840,4
4,0.003616,0.000804,0.004820,0.000983,gini,log2,best,"{'criterion': 'gini', 'max_features': 'log2', ...",0.945100,0.942166,0.943651,0.962264,0.962573,0.951151,0.009247,8
5,0.003863,0.001193,0.004824,0.000984,gini,log2,random,"{'criterion': 'gini', 'max_features': 'log2', ...",0.981569,0.961755,0.981217,0.981217,0.981217,0.977395,0.007821,2
6,0.005216,0.001165,0.007055,0.001715,entropy,auto,best,"{'criterion': 'entropy', 'max_features': 'auto...",0.963284,0.943041,0.962573,0.943093,0.962264,0.954851,0.009627,7
7,0.005256,0.001663,0.005181,0.001762,entropy,auto,random,"{'criterion': 'entropy', 'max_features': 'auto...",0.981569,0.924528,0.962264,0.981031,1.000000,0.969879,0.025624,5
8,0.004003,0.000261,0.004639,0.000813,entropy,sqrt,best,"{'criterion': 'entropy', 'max_features': 'sqrt...",0.926567,0.867097,0.962264,0.943651,0.962264,0.932369,0.035239,12
9,0.003217,0.000985,0.004724,0.001080,entropy,sqrt,random,"{'criterion': 'entropy', 'max_features': 'sqrt...",1.000000,0.962264,0.925524,0.962264,0.981217,0.966254,0.024712,6
10,0.003117,0.001077,0.004393,0.002409,entropy,log2,best,"{'criterion': 'entropy', 'max_features': 'log2...",0.981569,0.943041,0.943651,1.000000,1.000000,0.973652,0.025644,3
11,0.000905,0.001121,0.003900,0.004800,entropy,log2,random,"{'criterion': 'entropy', 'max_features': 'log2...",0.962963,0.981014,0.981217,0.962573,1.000000,0.977553,0.013904,1

In [23]:

classifier.predict([[48,80,1,0,121,36,1.2,137,4.5,15,44,7800,5.2,
                     1,0,0,0,
                     1,1,
                     0,0,
                     1,1,0,
                     1,0,0]])

NameError: name 'classifier' is not defined

In [24]:
table=pd.DataFrame.from_dict(re)

In [25]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_splitter,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.018285,0.006979,0.006425,0.000805,gini,auto,best,"{'criterion': 'gini', 'max_features': 'auto', ...",0.945100,0.924528,0.907035,0.943093,0.943093,0.932570,0.014800,11
1,0.009087,0.001674,0.005823,0.001141,gini,auto,random,"{'criterion': 'gini', 'max_features': 'auto', ...",0.925035,0.961755,0.981217,0.906705,0.943651,0.943673,0.026270,9
2,0.004771,0.001033,0.005992,0.001342,gini,sqrt,best,"{'criterion': 'gini', 'max_features': 'sqrt', ...",0.926978,0.962264,0.925524,0.903887,0.981031,0.939937,0.027794,10
3,0.003815,0.000190,0.005273,0.000925,gini,sqrt,random,"{'criterion': 'gini', 'max_features': 'sqrt', ...",0.926567,0.981014,0.981217,0.981217,0.981217,0.970246,0.021840,4
4,0.003616,0.000804,0.004820,0.000983,gini,log2,best,"{'criterion': 'gini', 'max_features': 'log2', ...",0.945100,0.942166,0.943651,0.962264,0.962573,0.951151,0.009247,8
5,0.003863,0.001193,0.004824,0.000984,gini,log2,random,"{'criterion': 'gini', 'max_features': 'log2', ...",0.981569,0.961755,0.981217,0.981217,0.981217,0.977395,0.007821,2
6,0.005216,0.001165,0.007055,0.001715,entropy,auto,best,"{'criterion': 'entropy', 'max_features': 'auto...",0.963284,0.943041,0.962573,0.943093,0.962264,0.954851,0.009627,7
7,0.005256,0.001663,0.005181,0.001762,entropy,auto,random,"{'criterion': 'entropy', 'max_features': 'auto...",0.981569,0.924528,0.962264,0.981031,1.000000,0.969879,0.025624,5
8,0.004003,0.000261,0.004639,0.000813,entropy,sqrt,best,"{'criterion': 'entropy', 'max_features': 'sqrt...",0.926567,0.867097,0.962264,0.943651,0.962264,0.932369,0.035239,12
9,0.003217,0.000985,0.004724,0.001080,entropy,sqrt,random,"{'criterion': 'entropy', 'max_features': 'sqrt...",1.000000,0.962264,0.925524,0.962264,0.981217,0.966254,0.024712,6
10,0.003117,0.001077,0.004393,0.002409,entropy,log2,best,"{'criterion': 'entropy', 'max_features': 'log2...",0.981569,0.943041,0.943651,1.000000,1.000000,0.973652,0.025644,3
11,0.000905,0.001121,0.003900,0.004800,entropy,log2,random,"{'criterion': 'entropy', 'max_features': 'log2...",0.962963,0.981014,0.981217,0.962573,1.000000,0.977553,0.013904,1

In [26]:
# print best parameter after tuning 
#print(grid.best_params_) 
re=grid.cv_results_
#print(re)
grid_predictions = grid.predict(X_test) 
   

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, grid_predictions)



# print classification report 
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, grid_predictions)

In [27]:
from sklearn.metrics import roc_auc_score

roc_auc_score(y_test, grid.predict_proba(X_test)[:,1])

0.9939024390243902