In [1]:
#importing the Libraies
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
# Reading the Dataset
dataset = pd.read_csv('CKD.csv')

In [3]:
dataset

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,2.000000,76.459948,c,3.0,0.0,normal,abnormal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,yes,no,yes
1,3.000000,76.459948,c,2.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,34.000000,12300.000000,4.705597,no,no,no,yes,poor,no,yes
2,4.000000,76.459948,a,1.0,0.0,normal,normal,notpresent,notpresent,99.000000,...,34.000000,8408.191126,4.705597,no,no,no,yes,poor,no,yes
3,5.000000,76.459948,d,1.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,poor,yes,yes
4,5.000000,50.000000,c,0.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,36.000000,12400.000000,4.705597,no,no,no,yes,poor,no,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,219.000000,...,37.000000,9800.000000,4.400000,no,no,no,yes,poor,no,yes
395,51.492308,70.000000,c,0.0,2.0,normal,normal,notpresent,notpresent,220.000000,...,27.000000,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
396,51.492308,70.000000,c,3.0,0.0,normal,normal,notpresent,notpresent,110.000000,...,26.000000,9200.000000,3.400000,yes,yes,no,poor,poor,no,yes
397,51.492308,90.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,207.000000,...,38.868902,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
398,51.492308,80.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,100.000000,...,53.000000,8500.000000,4.900000,no,no,no,yes,poor,no,no

In [4]:
print(dataset.columns)

Index(['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr', 'bu',
       'sc', 'sod', 'pot', 'hrmo', 'pcv', 'wc', 'rc', 'htn', 'dm', 'cad',
       'appet', 'pe', 'ane', 'classification'],
      dtype='object')

In [5]:
dataset=pd.get_dummies(dataset,drop_first=True)

In [6]:
dataset

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes,classification_yes
0,2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,False,False,False,False,False,False,True,True,False,True
1,3.000000,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,True,False,False,False,False,False,True,False,False,True
2,4.000000,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,True,False,False,False,False,False,True,False,False,True
3,5.000000,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,True,False,False,False,False,False,True,False,True,True
4,5.000000,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,True,False,False,False,False,False,True,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0.0,0.0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,...,True,False,False,False,False,False,True,False,False,True
395,51.492308,70.000000,0.0,2.0,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,...,True,False,False,True,True,False,True,False,True,True
396,51.492308,70.000000,3.0,0.0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,...,True,False,False,True,True,False,False,False,False,True
397,51.492308,90.000000,0.0,0.0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,...,True,False,False,True,True,False,True,False,True,True
398,51.492308,80.000000,0.0,0.0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,...,True,False,False,False,False,False,True,False,False,False

In [7]:
#X (Input features):
indep=dataset[['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes', ]]
dep=dataset['classification_yes']

In [8]:
indep

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,rbc_normal,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes
0,2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,True,False,False,False,False,False,False,True,True,False
1,3.000000,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,True,True,False,False,False,False,False,True,False,False
2,4.000000,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,True,True,False,False,False,False,False,True,False,False
3,5.000000,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,True,True,False,False,False,False,False,True,False,True
4,5.000000,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,True,True,False,False,False,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0.0,0.0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,...,True,True,False,False,False,False,False,True,False,False
395,51.492308,70.000000,0.0,2.0,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,...,True,True,False,False,True,True,False,True,False,True
396,51.492308,70.000000,3.0,0.0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,...,True,True,False,False,True,True,False,False,False,False
397,51.492308,90.000000,0.0,0.0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,...,True,True,False,False,True,True,False,True,False,True
398,51.492308,80.000000,0.0,0.0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,...,True,True,False,False,False,False,False,True,False,False

In [9]:
dep

0       True
1       True
2       True
3       True
4       True
       ...
394     True
395     True
396     True
397     True
398    False
Name: classification_yes, Length: 399, dtype: bool

In [10]:
#split into training set and test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(indep, dep, test_size = 1/3, random_state = 0)

In [11]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [12]:
from sklearn.svm import SVC

In [13]:
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV

# Define parameter grid
param_grid = {
    'C': [0.1, 1, 10, 100],
    'kernel': ['linear', 'rbf', 'poly', 'sigmoid'],
    'gamma': ['scale', 'auto'],   # 'scale' is default
    'degree': [2, 3, 4]           # only relevant for 'poly' kernel
}

# Create GridSearchCV object
grid = GridSearchCV(SVC(), param_grid, refit=True, verbose=3, n_jobs=-1, scoring='f1_weighted')

# Fit to training data
grid.fit(X_train, y_train)

# Best parameters
print("Best Parameters:", grid.best_params_)

Fitting 5 folds for each of 96 candidates, totalling 480 fits
Best Parameters: {'C': 10, 'degree': 2, 'gamma': 'scale', 'kernel': 'sigmoid'}

In [14]:
# print best parameter after tuning 
#print(grid.best_params_) 
re=grid.cv_results_
#print(re)
grid_predictions = grid.predict(X_test) 
   

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, grid_predictions)



# print classification report 
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, grid_predictions)

In [15]:

from sklearn.metrics import f1_score
f1_macro=f1_score(y_test,grid_predictions,average='weighted')
print("The f1_macro value for best parameter {}:".format(grid.best_params_),f1_macro)

The f1_macro value for best parameter {'C': 10, 'degree': 2, 'gamma': 'scale', 'kernel': 'sigmoid'}: 0.9924946382275899

In [16]:
print("The confusion Matrix:\n",cm)

The confusion Matrix:
 [[51  0]
 [ 1 81]]

In [17]:
print("The report:\n",clf_report)

The report:
               precision    recall  f1-score   support

       False       0.98      1.00      0.99        51
        True       1.00      0.99      0.99        82

    accuracy                           0.99       133
   macro avg       0.99      0.99      0.99       133
weighted avg       0.99      0.99      0.99       133

In [18]:
print("The report:\n",clf_report)

The report:
               precision    recall  f1-score   support

       False       0.98      1.00      0.99        51
        True       1.00      0.99      0.99        82

    accuracy                           0.99       133
   macro avg       0.99      0.99      0.99       133
weighted avg       0.99      0.99      0.99       133

In [20]:
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import roc_auc_score

# Grid search with probability enabled
param_grid = {
    'C': [0.1, 1, 10],
    'kernel': ['linear', 'rbf'],
    'gamma': ['scale', 'auto']
}

grid = GridSearchCV(SVC(probability=True), param_grid, refit=True, verbose=3, n_jobs=-1, scoring='f1_weighted')

# Fit model
grid.fit(X_train, y_train)

# Predict probabilities
y_proba = grid.predict_proba(X_test)[:, 1]  # probability for positive class

# ROC AUC
roc_score = roc_auc_score(y_test, y_proba)
print("ROC AUC:", roc_score)

Fitting 5 folds for each of 12 candidates, totalling 60 fits
ROC AUC: 0.9992826398852224

In [21]:
table=pd.DataFrame.from_dict(re)

In [22]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_degree,param_gamma,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.010301,0.008025,0.006586,0.001226,0.1,2,scale,linear,"{'C': 0.1, 'degree': 2, 'gamma': 'scale', 'ker...",0.981569,0.962264,1.000000,1.000000,1.000000,0.988767,0.015052,14
1,0.007859,0.001277,0.008807,0.002240,0.1,2,scale,rbf,"{'C': 0.1, 'degree': 2, 'gamma': 'scale', 'ker...",0.926978,0.981014,0.962573,1.000000,0.981217,0.970356,0.024708,61
2,0.008458,0.000714,0.007970,0.000968,0.1,2,scale,poly,"{'C': 0.1, 'degree': 2, 'gamma': 'scale', 'ker...",0.486532,0.492321,0.477841,0.477841,0.468812,0.480670,0.008084,96
3,0.006766,0.001773,0.005935,0.001226,0.1,2,scale,sigmoid,"{'C': 0.1, 'degree': 2, 'gamma': 'scale', 'ker...",0.945100,0.981233,0.962573,0.981217,0.981217,0.970268,0.014509,67
4,0.003694,0.000593,0.005628,0.000516,0.1,2,auto,linear,"{'C': 0.1, 'degree': 2, 'gamma': 'auto', 'kern...",0.981569,0.962264,1.000000,1.000000,1.000000,0.988767,0.015052,14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91,0.005366,0.001998,0.003244,0.000583,100,4,scale,sigmoid,"{'C': 100, 'degree': 4, 'gamma': 'scale', 'ker...",0.981569,0.943699,0.944023,0.981031,1.000000,0.970065,0.022459,73
92,0.004181,0.004086,0.002405,0.002944,100,4,auto,linear,"{'C': 100, 'degree': 4, 'gamma': 'auto', 'kern...",0.981569,0.962636,0.962573,0.981031,0.981217,0.973805,0.009147,49
93,0.002877,0.001624,0.001646,0.002016,100,4,auto,rbf,"{'C': 100, 'degree': 4, 'gamma': 'auto', 'kern...",0.963284,0.981014,1.000000,0.981031,1.000000,0.985066,0.013807,29
94,0.007672,0.002760,0.004538,0.002586,100,4,auto,poly,"{'C': 100, 'degree': 4, 'gamma': 'auto', 'kern...",0.926978,0.870362,0.888515,0.981217,0.794081,0.892231,0.062051,87
95,0.003659,0.003054,0.001623,0.002761,100,4,auto,sigmoid,"{'C': 100, 'degree': 4, 'gamma': 'auto', 'kern...",0.981569,0.943699,0.944023,0.981031,1.000000,0.970065,0.022459,73

In [24]:

grid.predict([[48,80,1,0,121,36,1.2,137,4.5,15,44,7800,5.2,
                     1,0,0,0,
                     1,1,
                     0,0,
                     1,1,0,
                     1,0,0]])

array([ True])

In [25]:
table=pd.DataFrame.from_dict(re)

In [26]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_degree,param_gamma,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.010301,0.008025,0.006586,0.001226,0.1,2,scale,linear,"{'C': 0.1, 'degree': 2, 'gamma': 'scale', 'ker...",0.981569,0.962264,1.000000,1.000000,1.000000,0.988767,0.015052,14
1,0.007859,0.001277,0.008807,0.002240,0.1,2,scale,rbf,"{'C': 0.1, 'degree': 2, 'gamma': 'scale', 'ker...",0.926978,0.981014,0.962573,1.000000,0.981217,0.970356,0.024708,61
2,0.008458,0.000714,0.007970,0.000968,0.1,2,scale,poly,"{'C': 0.1, 'degree': 2, 'gamma': 'scale', 'ker...",0.486532,0.492321,0.477841,0.477841,0.468812,0.480670,0.008084,96
3,0.006766,0.001773,0.005935,0.001226,0.1,2,scale,sigmoid,"{'C': 0.1, 'degree': 2, 'gamma': 'scale', 'ker...",0.945100,0.981233,0.962573,0.981217,0.981217,0.970268,0.014509,67
4,0.003694,0.000593,0.005628,0.000516,0.1,2,auto,linear,"{'C': 0.1, 'degree': 2, 'gamma': 'auto', 'kern...",0.981569,0.962264,1.000000,1.000000,1.000000,0.988767,0.015052,14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91,0.005366,0.001998,0.003244,0.000583,100,4,scale,sigmoid,"{'C': 100, 'degree': 4, 'gamma': 'scale', 'ker...",0.981569,0.943699,0.944023,0.981031,1.000000,0.970065,0.022459,73
92,0.004181,0.004086,0.002405,0.002944,100,4,auto,linear,"{'C': 100, 'degree': 4, 'gamma': 'auto', 'kern...",0.981569,0.962636,0.962573,0.981031,0.981217,0.973805,0.009147,49
93,0.002877,0.001624,0.001646,0.002016,100,4,auto,rbf,"{'C': 100, 'degree': 4, 'gamma': 'auto', 'kern...",0.963284,0.981014,1.000000,0.981031,1.000000,0.985066,0.013807,29
94,0.007672,0.002760,0.004538,0.002586,100,4,auto,poly,"{'C': 100, 'degree': 4, 'gamma': 'auto', 'kern...",0.926978,0.870362,0.888515,0.981217,0.794081,0.892231,0.062051,87
95,0.003659,0.003054,0.001623,0.002761,100,4,auto,sigmoid,"{'C': 100, 'degree': 4, 'gamma': 'auto', 'kern...",0.981569,0.943699,0.944023,0.981031,1.000000,0.970065,0.022459,73

In [27]:
# print best parameter after tuning 
#print(grid.best_params_) 
re=grid.cv_results_
#print(re)
grid_predictions = grid.predict(X_test) 
   

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, grid_predictions)



# print classification report 
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, grid_predictions)

In [28]:
from sklearn.metrics import roc_auc_score

roc_auc_score(y_test, grid.predict_proba(X_test)[:,1])

0.9992826398852224